### ISSUE TITLE
The NodeInfoView is missing

### ISSUE THREAD

**Issue by markusguenther** [aertmann/history#3]
![bildschirmfoto 2018-05-02 um 16 27 01](https://user-images.githubusercontent.com/1014126/39529076-19480270-4e26-11e8-8d11-5a2e4079f7b2.png)

It seems that this feature is only working in the old UI. If I understand it right you need ember to get this.

Hope that I find some time for the ReactUI stuff :)

**Comment by aertmann** [comment]
Solved with #075143a6ba76a87b7a842a3a297baa60722194b6
